exclude = [
  '^http://127\.0\.0\.1:8088/$',
  '^https://img\.shields\.io/github/actions/workflow/status/mondeja/mkdocs-',
  '^https://github.com/mondeja/mkdocs-include-markdown-',
  'https://raw\.githubusercontent\.com/mondeja/',
  'https://github.com/user/repo'
]
exclude_path = ["lychee.toml"]
